### ISSUE TITLE
Latest GZ release is broken.

### ISSUE THREAD

**Issue by nevack** [Naunter/BT_BlockLists#16]
`tar` tells https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz is invalid archive.
Checksum:
`0d25e429de8f1ac5cc51ab3bb99aee326297b545a019e0a58fffc8ade7ae67db  bt_blocklists.gz`
File size:
`680318 bytes`

**Comment by Naunter** [comment]
The `bt_blocklists.gz` file is not corrupted, but you use the wrong command to view the file.

`.tar`, archive by `tar` but no compress.
`.gz`, compress by `gzip` but no archive.
`.tar.gz`, compress by `gzip` and archive with `tar`.

You can use `tar` command to interact with `.tar` and `.tar.gz` files, but `.gz` is a file format by `gzip`. If you want to interact with a `.gz` file you can try command `gzip` or `gnuzip` .

**Comment by nevack** [comment]
> The `bt_blocklists.gz` file is not corrupted, but you use the wrong command to view the file.

Sorry, you are right.
Feel totally stupid right now.
Thanks for thorough explanation by the way.
